/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculovigasre.Vistas;

import com.mycompany.calculovigasre.CompatibilidadEnIntervencionesHistoricas;
import com.mycompany.calculovigasre.DeprecatedControladores.CompatibilidadControlador;
//import com.mycompany.calculovigasre.Controladores.AltaControlador;
//import com.mycompany.calculovigasre.Controladores.CompatibilidadControlador;
//import com.mycompany.calculovigasre.Controladores.EstudioControlador;
//import com.mycompany.calculovigasre.Controladores.InfoControlador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JTextField;

/**
 *
 * @author ifons
 */
public class CompatibilidadVistaRe extends javax.swing.JFrame {
    private static CompatibilidadEnIntervencionesHistoricas a= new CompatibilidadEnIntervencionesHistoricas();
    /**
     * Creates new form CompatibilidadVistaRe
     */
    public CompatibilidadVistaRe(String titulo) {
        super(titulo);
	initComponents();	
        info.addActionListener(new Escuchador1());
        info1viga.addActionListener(new Escuchador2());
        infoestudio.addActionListener(new Escuchador3());
        altaViga.addActionListener(new Escuchador4());
        infoFactor.addActionListener(new Escuchador5());
        altaCali.addActionListener(new Escuchador5());
        vigaTiemp.addActionListener(new Escuchador5());
        reempViga.addActionListener(new Escuchador5());
        bajaEst.addActionListener(new Escuchador5());
        bajaViga.addActionListener(new Escuchador5());
        mayF.addActionListener(new Escuchador5());
        minF.addActionListener(new Escuchador5());
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        claveTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTextArea();
        info = new javax.swing.JButton();
        info1viga = new javax.swing.JButton();
        infoestudio = new javax.swing.JButton();
        infoFactor = new javax.swing.JButton();
        altaCali = new javax.swing.JButton();
        altaViga = new javax.swing.JButton();
        bajaViga = new javax.swing.JButton();
        tipoTxt = new javax.swing.JTextField();
        tiempoTxt = new javax.swing.JTextField();
        cargaBx = new javax.swing.JComboBox<>();
        bajaEst = new javax.swing.JButton();
        vigaTiemp = new javax.swing.JButton();
        reempViga = new javax.swing.JButton();
        minF = new javax.swing.JButton();
        mayF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(594, 472));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Clave:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Calidad: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Carga:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tiempo:");

        claveTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        claveTxt.setToolTipText("");

        res.setColumns(20);
        res.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        res.setRows(5);
        jScrollPane1.setViewportView(res);

        info.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        info.setText("Información de la obra");

        info1viga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        info1viga.setText("1. Info. viga");

        infoestudio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoestudio.setText("2. Info. estudio");

        infoFactor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoFactor.setText("3. Info. factor");

        altaCali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        altaCali.setText("4. Alta calidad");

        altaViga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        altaViga.setText("5. Alta viga");

        bajaViga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bajaViga.setText("6. Baja viga");

        tipoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tiempoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cargaBx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cargaBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 dias", "14 dias", "28 dias" }));

        bajaEst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bajaEst.setText("7. Baja estudio");

        vigaTiemp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vigaTiemp.setText("8. Deterioro viga");

        reempViga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reempViga.setText("9. Reemplazar viga");

        minF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        minF.setText("10. Factor menor");

        mayF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mayF.setText("11. Factor mayor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(reempViga)
                        .addGap(18, 18, 18)
                        .addComponent(minF)
                        .addGap(18, 18, 18)
                        .addComponent(mayF))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altaViga)
                            .addComponent(info1viga, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(infoestudio)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bajaViga)
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoFactor)
                                .addGap(18, 18, 18)
                                .addComponent(altaCali))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bajaEst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vigaTiemp))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(claveTxt)
                            .addComponent(tipoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))))
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cargaBx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tiempoTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(info)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claveTxt)
                    .addComponent(jLabel3)
                    .addComponent(cargaBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipoTxt)
                    .addComponent(jLabel4)
                    .addComponent(tiempoTxt))
                .addGap(18, 18, 18)
                .addComponent(info)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info1viga)
                    .addComponent(infoestudio)
                    .addComponent(infoFactor)
                    .addComponent(altaCali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bajaEst)
                    .addComponent(altaViga)
                    .addComponent(bajaViga)
                    .addComponent(vigaTiemp))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reempViga)
                    .addComponent(minF)
                    .addComponent(mayF))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private class Escuchador1 implements ActionListener{
		public void actionPerformed(ActionEvent arg0) {
			String r;
			
			r=a.toString();
			
			res.setText(r);
		}
	}
		
	private class Escuchador2 implements ActionListener{
		public void actionPerformed(ActionEvent arg1) {
			String clave=claveTxt.getText();
			
			if(!clave.equals("")) {
				InfoVistaRe q = new InfoVistaRe("Viga",a,clave);
                                q.setVisible(true);
			}
			else {
				res.setText("Inserta clave");
			}
		}
	}
	
	private class Escuchador3 implements ActionListener{
		public void actionPerformed(ActionEvent arg2) {
			String tip=tipoTxt.getText();
			
			if(!tip.equals("")) {
				EstudioVistaRe c= new EstudioVistaRe("Estudio",a,tip);
                                c.setVisible(true);
			}
			else {
				res.setText("Inseta la calidad");
			}
		}
	}
		
	private class Escuchador4 implements ActionListener{
		public void actionPerformed(ActionEvent arg3) {
			AltaVistaRe f= new AltaVistaRe("Alta",a);
                        f.setVisible(true);
		}
	}
		
	private class Escuchador5 implements ActionListener{
		public void actionPerformed(ActionEvent arg4) {
			
			String r;
			String clv,tip,tiemp,car;
			int clv1,tip1,tiemp1,car1;
			String infor="";
			boolean d;
			
			r=arg4.getActionCommand();
			
			switch(r.charAt(0)) {
				case '3':
					tip=tipoTxt.getText();
					tiemp=tiempoTxt.getText();
					car=(String) cargaBx.getSelectedItem();
					
					if(!tip.equals("")&&!tiemp.equals("")) {
						tip1=Integer.parseInt(tip);
						tiemp1=Integer.parseInt(tiemp);
						if(cargaBx.getSelectedIndex()==0) {
							car1=Integer.parseInt(car.substring(0,1));
						}
						else {
							car1=Integer.parseInt(car.substring(0, 2));
						}
						infor="" + a.getUnFactor(tip1, tiemp1, car1);
					}
					else {
						infor="Inserta el tipo, tiempo y carga";
					}
					
					break;
				case '4':
					tip=tipoTxt.getText();
					
					if(!tip.equals("")) {
						tip1=Integer.parseInt(tip);
					
						d=a.altaCalidad(tip1);
					
						if(d) {
							infor="Registrado con exito";
						}
						else {
							infor="No se registro";
						}
					}
					else {
						infor="Inserta un tipo";
					}
					break;
				case 'D':
					tiemp=tiempoTxt.getText();
					clv=claveTxt.getText();
					car=(String) cargaBx.getSelectedItem();
					
					if(!tiemp.equals("")&&!clv.equals("")) {
						tiemp1=Integer.parseInt(tiemp);
						clv1=Integer.parseInt(clv);
						if(cargaBx.getSelectedIndex()==0) {
							car1=Integer.parseInt(car.substring(0,1));
						}
						else {
							car1=Integer.parseInt(car.substring(0, 2));
						}
						
						infor=a.vigaEnElTiempo(clv1, tiemp1, car1);
					}
					else {
						infor="Inserta la clave, tiempo y carga";
					}
					break;
				case 'R':
					clv=claveTxt.getText();
					tiemp=tiempoTxt.getText();
					car=(String) cargaBx.getSelectedItem();
					
					if(!clv.equals("")&&!tiemp.equals("")) {
						clv1=Integer.parseInt(clv);
						tiemp1=Integer.parseInt(tiemp);
						if(cargaBx.getSelectedIndex()==0) {
							car1=Integer.parseInt(car.substring(0,1));
						}
						else {
							car1=Integer.parseInt(car.substring(0, 2));
						}
						
						infor=a.reemplazaViga(clv1);
					}
					else {
						infor="Inserta la clave, tiempo y carga";
					}
					break;
				case '5':
					tip=tipoTxt.getText();
					tiemp=tiempoTxt.getText();
					
					if(!tip.equals("")&&!tiemp.equals("")) {
						tip1=Integer.parseInt(tip);
						tiemp1=Integer.parseInt(tiemp);
						
						d=a.bajaEstudio(tip1, tiemp1);
						
						if(d) {
							infor="Baja exitosa";
						}
						else {
							infor="No se encontro";
						}
					}
					else {
						infor="Inserta tipo y tiempo";
					}
					break;
				case '6':
					clv=claveTxt.getText();
					
					if(!clv.equals("")) {
						clv1=Integer.parseInt(clv);
						
						d=a.bajaViga(clv1);
						
						if(d) {
							infor="Baja exitosa";
						}
						else {
							infor="No se encontro";
						}
					}
					else {
						infor="Inserta la clave";
					}
					break;
				case 'F':
					infor="" + a.getMayFactor();
					break;
				case '7':
					infor="" + a.gatMinFact();
					break;
			}
			
			res.setText(infor);
			
		}
        }

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompatibilidadVistaRe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompatibilidadVistaRe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompatibilidadVistaRe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompatibilidadVistaRe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CompatibilidadVistaRe b= new CompatibilidadVistaRe("Compatibilidad");
		b.setVisible(true);
		int numC, c, numM,m, numS, numV, ba, mod, s, p, cl, inicio, fin, carg;
		double f1, f2, f3, r;
		
		File datos = new File("src/main/java/Files/CasaVirreinal.txt");
		
		try (Scanner lec= new Scanner(datos)){
			a.setNomPatrimonioHistorico("Casa Virreinal");
			
			numC= lec.nextInt();
			
			for(int i=0; i<numC; i++) {
				c=lec.nextInt();
				a.altaCalidad(c);
			}
			
			for(int i=0; i<numC; i++) {
				numM= lec.nextInt();
				c=lec.nextInt();
				for(int j=0; j<numM; j++) {
					m=lec.nextInt();
					f1=lec.nextDouble();
					f2= lec.nextDouble();
					f3=lec.nextDouble();
					
					a.altaEstudio(c, m, f1, f2, f3);
				}
			}
			
			numS= lec.nextInt();
			
			for(int i=0; i<numS; i++) {
				numV=lec.nextInt();
				c=lec.nextInt();
				ba=lec.nextInt();
				r=lec.nextDouble();
				mod=lec.nextInt();
				s=lec.nextInt();
				
				for(int j=0; j<numV; j++) {
					
					a.altaViga(c, ba, r, mod, s);
				}
				inicio=lec.nextInt();
				fin=lec.nextInt();
				p=lec.nextInt();
				cl=lec.nextInt();
				m=lec.nextInt();
				carg=lec.nextInt();
				
				while(inicio<=fin) {
					
					a.setRigidez(inicio, cl, p);
					a.vigaEnElTiempo(inicio, m, carg);
					
					inicio++;
				}
			}
			
			numV=lec.nextInt();
			
			for(int i=0; i<numV; i++) {
				cl=lec.nextInt();
				
				a.reemplazaViga(cl);
			}
			
		}
		catch(FileNotFoundException err){
			System.err.println(err);
			System.exit(-1);
		}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaCali;
    private javax.swing.JButton altaViga;
    private javax.swing.JButton bajaEst;
    private javax.swing.JButton bajaViga;
    private javax.swing.JComboBox<String> cargaBx;
    private javax.swing.JTextField claveTxt;
    private javax.swing.JButton info;
    private javax.swing.JButton info1viga;
    private javax.swing.JButton infoFactor;
    private javax.swing.JButton infoestudio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mayF;
    private javax.swing.JButton minF;
    private javax.swing.JButton reempViga;
    private javax.swing.JTextArea res;
    private javax.swing.JTextField tiempoTxt;
    private javax.swing.JTextField tipoTxt;
    private javax.swing.JButton vigaTiemp;
    // End of variables declaration//GEN-END:variables
}
