/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculovigasre.Vistas;

import com.mycompany.calculovigasre.CompatibilidadEnIntervencionesHistoricas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
//import com.mycompany.calculovigasre.Controladores.InfoControlador;

/**
 *
 * @author ifons
 */
public class InfoVistaRe extends javax.swing.JFrame {
    private static CompatibilidadEnIntervencionesHistoricas b;
    private static int claveNum;
    /**
     * Creates new form InfoVistaRe
     */
    public InfoVistaRe(String titulo,CompatibilidadEnIntervencionesHistoricas b,String clave) {
        super(titulo);
	initComponents();	
        this.b=b;
        inercia.addActionListener(new Escuchador7());
        reMod.addActionListener(new Escuchador7());
        areaA.addActionListener(new Escuchador7());
        areaAT.addActionListener(new Escuchador7());
        ejeN.addActionListener(new Escuchador7());
        inS.addActionListener(new Escuchador7());
        modSec.addActionListener(new Escuchador7());

        claveNum=Integer.parseInt(clave);

        infoViga.setText(b.getUnaViga(claveNum));
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        infoViga = new javax.swing.JTextArea();
        res = new javax.swing.JTextField();
        inercia = new javax.swing.JButton();
        reMod = new javax.swing.JButton();
        areaA = new javax.swing.JButton();
        areaAT = new javax.swing.JButton();
        ejeN = new javax.swing.JButton();
        inS = new javax.swing.JButton();
        modSec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 437));

        infoViga.setColumns(20);
        infoViga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoViga.setRows(5);
        jScrollPane1.setViewportView(infoViga);

        res.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        inercia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inercia.setText("Inercia");

        reMod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reMod.setText("Relación modular");

        areaA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaA.setText("Área de acero");

        areaAT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaAT.setText("Área de acero transformada");

        ejeN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ejeN.setText("Eje neutro");

        inS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inS.setText("Inercia de la sección");

        modSec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modSec.setText("Módulo de la sección");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inercia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reMod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaAT)
                            .addComponent(ejeN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inS, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modSec, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(res, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(res)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(inercia)
                .addGap(18, 18, 18)
                .addComponent(reMod)
                .addGap(18, 18, 18)
                .addComponent(areaA)
                .addGap(18, 18, 18)
                .addComponent(areaAT)
                .addGap(18, 18, 18)
                .addComponent(ejeN)
                .addGap(18, 18, 18)
                .addComponent(inS)
                .addGap(18, 18, 18)
                .addComponent(modSec)
                .addGap(44, 44, 44))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private class Escuchador7 implements ActionListener{
		public void actionPerformed(ActionEvent arg1) {
			String r;
			String info="-1";
			r=arg1.getActionCommand();
			
			switch(r.charAt(0)) {
				case 'I':
					info="" + b.inercia(claveNum);
					break;
				case 'R':
					info="" + b.relacionModular(claveNum);
					break;
				case 'A':
					info="" + b.areaDeAcero(claveNum);
					break;
				case '+':
					info="" + b.areaDeAceroTransformada(claveNum);
					break;
				case 'E':
					info="" + b.ejeNeutro(claveNum);
					break;
				case '*':
					info="" + b.inerciaDeLaSeccionAgrietada(claveNum);
					break;
				case'M':
					info="" + b.moduloDeSeccion(claveNum);
					break;
			}
			
			res.setText(info);
		}
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoVistaRe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoVistaRe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoVistaRe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoVistaRe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton areaA;
    private javax.swing.JButton areaAT;
    private javax.swing.JButton ejeN;
    private javax.swing.JButton inS;
    private javax.swing.JButton inercia;
    private javax.swing.JTextArea infoViga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modSec;
    private javax.swing.JButton reMod;
    private javax.swing.JTextField res;
    // End of variables declaration//GEN-END:variables
}
